options(scipen = 999) # function to stop showing scientific notations

df <- lynx # load the dataset

# Plotting a histogram with a normal curve
m<-mean(df)
std<-sqrt(var(df))
hist(df, prob = TRUE, 
     xlab="Lynxes Trapped", 
     main="normal curve over histogram")
curve(dnorm(x, mean=m, sd=std), 
      col="darkblue", lwd=2, add=TRUE, yaxt="n")

# basic plot of the lynx trappings with highlighted local maximums
plot(lynx, ylab='Lynx Trappings', ylim = c(0, 7200))

# Create data vectors
a <- c(1828, 1838, 1848, 1857, 1866, 1875, 1885, 1895, 1904, 1913, 1916, 1925, 1934)
b <- c(window(lynx, 1828, c(1828, 1)), window(lynx, 1838, c(1838, 1)), window(lynx, 1848, c(1848, 1)), 
       window(lynx, 1857, c(1857, 1)), window(lynx, 1866, c(1866, 1)), window(lynx, 1875, c(1875, 1)), 
       window(lynx, 1885, c(1885, 1)), window(lynx, 1895, c(1895, 1)),window(lynx, 1904, c(1904, 1)),
       window(lynx, 1913, c(1913, 1)), window(lynx, 1916, c(1916, 1)), window(lynx, 1925, c(1925, 1)),
       window(lynx, 1934, c(1934, 1)))

# Add the local maximum points
points(x = a,
       y = b,
       col = 'red')

# Add id labels
text(x = a, 
     y = b,
     labels = a, 
     pos = 3, 
     cex = 0.7, 
     font = 2) 

######################################################################
############################ Approach 1 ##############################
######################################################################

acf(lynx, lag.max = 70)
pacf(lynx, lag.max = 70)

# Spectrum function checks the optimum period for the data
spectrum(lynx)
# Add the local maximum points
a <- c(0.1, 0.108333333) # highlighting the two peaks in the plot
b <- c(39718652.61, 37928771.24)
points(x = a,
       y = b,
       col = 'red')

spectrum(lynx)$freq
spectrum(lynx)$spec

# Finding the optimum period for the data

acf(diff(lynx, lag = 9), lag.max = 70)
pacf(diff(lynx, lag = 9), lag.max = 70)

acf(diff(lynx, lag = 10), lag.max = 70)
pacf(diff(lynx, lag = 10), lag.max = 70)

# Preliminary ARIMA model according to the PACF plot with period = 9
acf(arima(lynx,order=c(2,0,0),seasonal=list(order=c(0,1,0),period=9))$resid, lag.max=70)
pacf(arima(lynx,order=c(2,0,0),seasonal=list(order=c(0,1,0),period=9))$resid, lag.max=70)

# Final ARIMA model with white-noise residuals
arima(lynx,order=c(2,0,0),seasonal=list(order=c(1,1,0),period=9))

acf(arima(lynx,order=c(2,0,0),seasonal=list(order=c(1,1,0),period=9))$resid, lag.max=70)
pacf(arima(lynx,order=c(2,0,0),seasonal=list(order=c(1,1,0),period=9))$resid, lag.max=70)

# Making predictions for the next 2 seasonal cycles
predictions <- round(predict(arima(lynx,order=c(2,0,0),seasonal=list(order=c(1,1,0),period=9)), n.ahead=18)$pred, 0)
ts.plot(df, predictions, lty = c(1,1), col=c(1,2), ylab="Lynx Trappings")

# Comparing the results generated by those of the predict function (turns out to be exactly the same)
library(forecast)
plot(forecast(arima(lynx,order=c(2,0,0),seasonal=list(order=c(1,1,0),period=9)), h=18))

######################################################################
############################ Approach 2 ##############################
######################################################################

# Log transforming and plotting the lynx trappings data
log_lynx <- log(lynx)
plot(log_lynx, ylab = "log(lynx)")

acf(log_lynx, lag.max = 70)
pacf(log_lynx, lag.max = 70)

spectrum(log_lynx)
# Add the local maximum points
a <- c(0.1, 0.108333333)
b <- c(30.123923112, 31.709863295)
points(x = a,
       y = b,
       col = 'red')

spectrum(log_lynx)$freq
spectrum(log_lynx)$spec

acf(diff(log_lynx, lag = 9), lag.max = 70)
pacf(diff(log_lynx, lag = 9), lag.max = 70)

acf(diff(log_lynx, lag = 10), lag.max = 70)
pacf(diff(log_lynx, lag = 10), lag.max = 70)

# Preliminary ARIMA model according to the PACF plot with period = 10
acf(arima(log_lynx,order=c(9,0,0),seasonal=list(order=c(0,1,0),period=10))$resid, lag.max=70)
pacf(arima(log_lynx,order=c(9,0,0),seasonal=list(order=c(0,1,0),period=10))$resid, lag.max=70)

# 2nd fitted model from the results of the PACF plot above (turns out to be white noise)
# However, model too complex
acf(arima(log_lynx,order=c(9,0,0),seasonal=list(order=c(1,1,0),period=10))$resid, lag.max=70)
pacf(arima(log_lynx,order=c(9,0,0),seasonal=list(order=c(1,1,0),period=10))$resid, lag.max=70)

# Final ARIMA model with white-noise residuals
arima(log_lynx,order=c(2,0,3),seasonal=list(order=c(1,1,0),period=10))
acf(arima(log_lynx,order=c(2,0,3),seasonal=list(order=c(1,1,0),period=10))$resid, lag.max=70)
pacf(arima(log_lynx,order=c(2,0,3),seasonal=list(order=c(1,1,0),period=10))$resid, lag.max=70)

# Making predictions for the next 2 seasonal cycles
predictions <- round(exp(predict(arima(log_lynx,order=c(2,0,3),seasonal=list(order=c(1,1,0),period=10)), n.ahead=20)$pred), 0)
ts.plot(df, predictions, lty = c(1,1), col=c(1,2), ylab="Lynx Trappings")
